### ISSUE TITLE
Admin page URL

### ISSUE THREAD

**Issue by vulporuza** [ipeos-and-co/docker-spip#3]
Bonjour, 

Je viens de mettre en ligne un vieux site SPIP pour de l'archivage en montant votre image docker dans un docker-compose, exposé derrière un reverse proxy nginx. 

Globalement cela fonctionne pour le site public, et je vous en remercie. Cependant pour le site privé les URL des pages pointent vers une URL localhost:3001/ecrire... 
Je ne sais pas bien d'où vient le problème précisément (du container ou de SPIP qui n'utilise pas l'URL du site pour les pages privées).

Avez vous une idée là dessus ?

Mon docker-compose au passage:
```
version: "3.7"  

networks:
  spip:
    external: false

volumes:
  spip-data:
    driver: local

services:
  spip:
    image: ipeos/spip:latest
    container_name: spip
    environment:
      - SPIP_AUTO_INSTALL=1
      - SPIP_DB_SERVER=sqlite3
      - SPIP_DB_PREFIX=spip
    networks:
      - spip
    volumes:
      - spip-data:/var/www/html
    ports:
      - "3001:80"
    restart: unless-stopped
```

Et mon reverse proxy:
```
server {
    if ($host = xxx) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name xxx;

    # Enforce https
    return 301 https://$server_name:443$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name xxx;

    location / {
        proxy_pass http://localhost:3001;
    }
    ssl_certificate /etc/letsencrypt/live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/privkey.pem;
}
```
Merci par avance pour toute piste :)
